name: github CI
on: [push]
jobs:
  test_build_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests unitaires
        run: |
          pip install pytest
          pytest tests_unitaires.py
      - name: build docker image
        run:
          docker build -t test .
      - name: run docker image
        run:
          docker run test